apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: mysql-simple
spec:
    selector:
        matchLabels:
            app: mysql-simple
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: mysql-simple
        spec:
            containers:
                -   image: mysql:5.6
                    name: mysql
                    env:
                        # Use secret in real usage
                        -   name: MYSQL_ROOT_PASSWORD
                            value: root2020
                    ports:
                        -   containerPort: 3306
                            name: mysql-simple